import React, { memo } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Slider from '@react-native-community/slider';
import { Gauge, Play, Square, Trash2, Shuffle, Volume2, Waves, Repeat, Zap, RotateCcw } from 'lucide-react-native';
import { C, GROUP, RADIUS } from '../theme';
import { STEMS } from '../audio/sampleBank';

const Btn = ({ children, onPress, style }) => <Pressable onPress={onPress} android_disableSound style={[styles.btn, style]}>{children}</Pressable>;
export const Transport = memo(({ playing, onToggle, bpm, onTapTempo, tapCount, onClear, onRandom }) => <View style={styles.transport}><Btn onPress={onToggle} style={{ borderColor: playing ? C.lime : C.cyan }}>{playing ? <Square size={16} color={C.lime} /> : <Play size={18} color={C.cyan} fill={C.cyan} />}</Btn><View style={styles.bpm}><Text style={styles.bpmValue}>{Math.round(bpm)}</Text><Text style={styles.unit}>BPM</Text></View><Btn onPress={onTapTempo}><Gauge size={13} color={C.textDim} /><Text style={styles.small}>TAP {tapCount ? tapCount : ''}</Text></Btn><Btn onPress={onClear}><Trash2 size={13} color={C.textDim} /></Btn><Btn onPress={onRandom}><Shuffle size={13} color={C.textDim} /></Btn></View>);
export const LabeledSlider = memo(({ icon, label, value, min, max, step, onChange, format, accent = C.cyan }) => <View style={styles.sliderWrap}><View style={styles.sliderHead}><View style={styles.sliderLabel}>{icon}<Text style={styles.small}>{label}</Text></View><Text style={[styles.value, { color: accent }]}>{format(value)}</Text></View><Slider style={styles.slider} minimumValue={min} maximumValue={max} step={step} value={value} onValueChange={onChange} minimumTrackTintColor={accent} maximumTrackTintColor={C.line} thumbTintColor={accent} /></View>);
export const BpmSlider = memo(({ bpm, onChange }) => <LabeledSlider icon={<Gauge size={13} color={C.textDim} />} label="TEMPO" value={bpm} min={60} max={180} step={1} onChange={onChange} accent={C.lime} format={(v) => `${Math.round(v)} BPM`} />);
export const VolumeSlider = memo(({ volume, onChange }) => <LabeledSlider icon={<Volume2 size={13} color={C.textDim} />} label="MASTER" value={volume} min={0} max={1} step={0.01} onChange={onChange} format={(v) => `${Math.round(v * 100)}%`} />);
export const RateSlider = memo(({ rate, onChange }) => <LabeledSlider icon={<Waves size={13} color={C.textDim} />} label="PITCH / SPEED" value={rate} min={0.5} max={2} step={0.01} onChange={onChange} accent={C.magenta} format={(v) => `${v.toFixed(2)}x`} />);
export const StemBar = memo(({ activeStems, onToggle }) => <View style={styles.row}>{STEMS.map((s) => { const on = !!activeStems[s.id], accent = GROUP[s.group] || C.cyan; return <Btn key={s.id} onPress={() => onToggle(s.id)} style={{ borderColor: on ? accent : C.line, flex: 1 }}><Repeat size={12} color={on ? accent : C.textFaint} /><Text style={[styles.small, { color: on ? accent : C.textFaint }]}>{s.label}</Text></Btn>; })}</View>);
export const FxBar = memo(({ lpf, onLpf, echo, onEcho, onRiser, onVinyl }) => <View style={styles.row}><Btn onPress={onLpf} style={{ borderColor: lpf ? C.violet : C.line }}><Waves size={12} color={lpf ? C.violet : C.textDim} /><Text style={styles.small}>LO-PASS</Text></Btn><Btn onPress={onEcho} style={{ borderColor: echo ? C.amber : C.line }}><Waves size={12} color={echo ? C.amber : C.textDim} /><Text style={styles.small}>ECHO</Text></Btn><Btn onPress={onRiser}><Zap size={12} color={C.textDim} /><Text style={styles.small}>RISER</Text></Btn><Btn onPress={onVinyl}><RotateCcw size={12} color={C.textDim} /><Text style={styles.small}>BRAKE</Text></Btn></View>);
const styles = StyleSheet.create({ transport: { flexDirection: 'row', alignItems: 'center', gap: 7 }, btn: { minWidth: 40, height: 42, paddingHorizontal: 9, borderRadius: RADIUS.md, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 5 }, bpm: { height: 42, paddingHorizontal: 10, borderRadius: RADIUS.md, borderWidth: 1, borderColor: C.line, backgroundColor: C.panel, flexDirection: 'row', alignItems: 'baseline', gap: 3 }, bpmValue: { color: C.lime, fontSize: 19, fontWeight: '900' }, unit: { color: C.textFaint, fontSize: 8, fontWeight: '800' }, small: { color: C.textDim, fontSize: 9, fontWeight: '800', letterSpacing: 0.6 }, sliderWrap: { marginBottom: 4 }, sliderHead: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, sliderLabel: { flexDirection: 'row', alignItems: 'center', gap: 5 }, value: { fontSize: 11, fontWeight: '900' }, slider: { width: '100%', height: 32 }, row: { flexDirection: 'row', gap: 6 } });
